//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SummerTraining.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course_Schedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course_Schedule()
        {
            this.Regestered_In_The_Course = new HashSet<Regestered_In_The_Course>();
        }
    
        public int Course_Id { get; set; }
        public string Course_Title { get; set; }
        public string Description { get; set; }
        public string Language { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime Start_Time { get; set; }
        public System.DateTime End_Time { get; set; }
        public string Course_Status { get; set; }
        public int Seats_Number { get; set; }
        public string Course_Place { get; set; }
        public string User_Type { get; set; }
        public int Classification_Id { get; set; }
        public string Course_Type { get; set; }
        public int Certificate_Id { get; set; }
        public string Trainer_Name { get; set; }
    
        public virtual Certificate_Template Certificate_Template { get; set; }
        public virtual Course_Classification Course_Classification { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Regestered_In_The_Course> Regestered_In_The_Course { get; set; }
    }
}
