//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SummerTraining.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Support_Tickets
    {
        public int Ticket_No { get; set; }
        public string Tilte { get; set; }
        public string Content { get; set; }
        public int User_Id { get; set; }
        public System.DateTime Date { get; set; }
        public string Status { get; set; }
    
        public virtual User User { get; set; }
    }
}
