//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SummerTraining.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Regestered_In_The_Course = new HashSet<Regestered_In_The_Course>();
            this.Support_Tickets = new HashSet<Support_Tickets>();
        }
    
        public int User_Id { get; set; }
        public string AR_Name { get; set; }
        public string EN_Name { get; set; }
        public int Mobile { get; set; }
        public int Role_Id { get; set; }
        public string Degree { get; set; }
        public string Gender { get; set; }
        public string Section { get; set; }
        public int Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Regestered_In_The_Course> Regestered_In_The_Course { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Support_Tickets> Support_Tickets { get; set; }
        public virtual User_Role User_Role { get; set; }
    }
}
